### ISSUE TITLE
Set up GitHub Repository

### ISSUE THREAD

**Issue by TobiasGoetz** [DHBW-FN/tim21-computer-graphics#11]
# User Story
**As a** team member,
**I want** to create a GitHub repository with an initial commit,
**So that** we can start collaborating on the project.

## Acceptance Criteria
- [ ] A GitHub repository is created.
- [ ] Initial commit with necessary files is pushed to the repository.

## Tasks
- [ ] Set up a new repository on GitHub.
- [ ] Add initial files and folders.
- [ ] Make the first commit.

## Additional Information
No additional information.
