### ISSUE TITLE
Choose and Configure Development Tools

### ISSUE THREAD

**Issue by TobiasGoetz** [DHBW-FN/tim21-computer-graphics#13]
# User Story
**As a** team member,
**I want** to choose and configure the necessary development tools,
**So that** we can efficiently work on the project.

## Acceptance Criteria
- [x] Development tools (Blender, Three.js, etc.) are chosen based on project requirements.
- [x] Tools are properly configured and ready for use.

## Tasks
- [x] Research and choose appropriate development tools.
- [x] Install and configure selected tools.

## Additional Information
No additional information.
