### ISSUE TITLE
Integrate Eiffel Tower Model

### ISSUE THREAD

**Issue by TobiasGoetz** [DHBW-FN/tim21-computer-graphics#14]
# User Story
**As a** 3D modeler,
**I want** to import and position the Eiffel Tower model into the scene,
**So that** it becomes a prominent feature of the environment.

## Acceptance Criteria
- [x] Eiffel Tower model is accurately positioned in the scene.
- [x] Model is properly scaled and aligned with the surroundings.

## Tasks
- [x] Download a pre-existing 3D model of the Eiffel Tower.
- [x] Import the Eiffel Tower model into the scene.
- [x] Position and align the model for realistic integration.

### Models
[free-la-tour-eiffel.zip](https://github.com/DHBW-FN/tim21-computer-graphics/files/13125485/free-la-tour-eiffel.zip)
https://sketchfab.com/3d-models/eiffel-tower-model-3d-with-best-quality-c3391c293e70471e9a112f7855adcf2f

### Result
This is the blender file + required textures.
Use this as a guidance for future model integration but keep in mind, that you will have to probably re-do it as collaborating on blender files is near impossible.
https://www.icloud.com/iclouddrive/0f6EveCV0ItUY6XiYsIjOXEFA#World
