### ISSUE TITLE
Integrate House Models and Street Lamps

### ISSUE THREAD

**Issue by TobiasGoetz** [DHBW-FN/tim21-computer-graphics#15]
# User Story
**As a** 3D modeler,
**I want** to integrate pre-existing 3D models of houses into the environment,
**So that** the scene resembles a neighborhood around the Eiffel Tower.

## Acceptance Criteria
- [x] Houses models are accurately positioned and integrated into the scene.
- [x] Street Lamps are accurately positioned and integrated into the scene.
- [x] Models are properly scaled and aligned with the surroundings.

## Tasks
- [x] Download pre-existing 3D models of houses.
- [x] Import house models into the scene using ThreeJS.
- [x] Position and arrange the models to create rows of houses using ThreeJS.
- [x] Download pre-existing models of street lamps.
- [x] Import street lamp models into the scene using ThreeJS.
- [x] Position and arrange the street lamp models using ThreeJS.

## Additional Information
No additional information.
