### ISSUE TITLE
Integrate Bushes and Trees Models

### ISSUE THREAD

**Issue by TobiasGoetz** [DHBW-FN/tim21-computer-graphics#16]
# User Story
**As a** 3D modeler,
**I want** to integrate pre-existing 3D models of bushes and trees into the environment,
**So that** the scene feels more lively and detailed.

## Acceptance Criteria
- [x] Bushes and trees models are accurately positioned and integrated into the scene.
- [x] Models are properly scaled and aligned for a natural landscape.

## Tasks
- [x] Download pre-existing 3D models of bushes and trees.
- [x] Import the models into the scene.
- [x] Position and arrange the models to create a realistic environment.

### Possible models
- https://www.turbosquid.com/3d-models/3d-model-2021-pbr-australian-tea-tree-collection-melaleuca-alternifolia-1804778
- https://www.turbosquid.com/3d-models/3d-acacia-tree-vol-15blender-model-2106120
- https://www.turbosquid.com/3d-models/3d-xfrogplants-honey-locust-gledista-triacanthos-1734005
- https://www.turbosquid.com/3d-models/gentree-105-generic-tree-105-3d-model-2062795
- https://www.turbosquid.com/3d-models/gentree-103-generic-tree-103-3d-model-2062798
- https://www.turbosquid.com/3d-models/callistemon-tree-model-2062119
- https://www.turbosquid.com/3d-models/3d-nature-assets-pack-1808019
- https://www.turbosquid.com/3d-models/tree-3d-model-1778325
- https://www.turbosquid.com/3d-models/tree-blend-free/1054253
- https://free3d.com/3d-model/tree-pack-1-70853.html
- https://free3d.com/3d-model/hazelnut-bush-290678.html
- https://free3d.com/3d-model/small-bush-76246.html
- https://sketchfab.com/3d-models/maple-tree-4b27adcf92f644bdabf8ecc6c5bef399
- https://sketchfab.com/3d-models/low-poly-tree-scene-free-89daa5e21f0d4f08a59dba0d566e88bd
- https://sketchfab.com/3d-models/cliff-shrub-for-terrain-7a0f2bf2982c4ff8bacc67856fdbfae2
- https://sketchfab.com/3d-models/low-poly-shrub-small-texture-6e16ec47d7c246a69efffb9e857165ed

### Funny models
- https://sketchfab.com/3d-models/matilda-7ddedfb652bd4ea091bc3de27f98fc02
- https://sketchfab.com/3d-models/street-bin-2b359b9b474a421b9532dea5342bff25
- https://sketchfab.com/3d-models/burger-street-cart-7907ff981478432781515977a5f53a86
- https://sketchfab.com/3d-models/street-food-vendor-challenge-kokorec-141db37d07fc4ccba84ab5f38a8181b5
- https://sketchfab.com/3d-models/ice-cream-vendor-ca442a80aeb84e76a3582c84c1185ecf

### Used models
- https://www.turbosquid.com/3d-models/3d-acacia-tree-vol-15blender-model-2106120
- https://www.turbosquid.com/3d-models/gentree-105-generic-tree-105-3d-model-2062795
- https://www.turbosquid.com/3d-models/gentree-103-generic-tree-103-3d-model-2062798
- https://sketchfab.com/3d-models/low-poly-shrub-small-texture-6e16ec47d7c246a69efffb9e857165ed
- https://free3d.com/3d-model/small-bush-76246.html
- https://www.blenderkit.com/get-blenderkit/712109e8-7599-4036-8bc7-d4a25f2d4640/
- https://www.turbosquid.com/3d-models/callistemon-tree-model-2062119
