### ISSUE TITLE
Add Secondary Stationary Camera

### ISSUE THREAD

**Issue by TobiasGoetz** [DHBW-FN/tim21-computer-graphics#22]
# User Story
**As a** front-end developer,
**I want** to add a secondary stationary camera to the UI,
**So that** users have an overview of the Eiffel Tower from a fixed perspective.

## Acceptance Criteria
- [x] Secondary stationary camera is displayed in the UI.
- [x] Users can switch to view the Eiffel Tower from the stationary camera.

## Tasks
- [x] Create UI element for the secondary camera.
- [x] Implement functionality to switch between drone and stationary camera views.

## Additional Information
No additional information.
