### ISSUE TITLE
Simulate Daylight with Sunlight Source

### ISSUE THREAD

**Issue by TobiasGoetz** [DHBW-FN/tim21-computer-graphics#23]
# User Story
**As a** front-end developer,
**I want** to add a sunlight source to simulate daylight in the 3D scene,
**So that** users can experience the Eiffel Tower in daylight conditions.

## Acceptance Criteria
- [x] Sunlight source is integrated into the scene.
- [x] Scene accurately simulates daylight conditions.
- [x] Sun causes shadows

## Tasks
- [x] Implement a directional light source for simulating sunlight.
- [x] Adjust light intensity and color to achieve realistic daylight.

## Additional Information
There is an example in Thre.JS that can be used for the Sky.
Directional Lights might not work with shadows as mentioned by Danny
