### ISSUE TITLE
Implement Day-Night Transition

### ISSUE THREAD

**Issue by TobiasGoetz** [DHBW-FN/tim21-computer-graphics#25]
# User Story
**As a** front-end developer,
**I want** to develop functionality for a seamless transition between day and night,
**So that** users can experience the changing lighting conditions.

## Acceptance Criteria
- [x] Users can transition between day and night within the scene.

## Tasks
- [x] Implement a transition mechanism triggered by user interaction.
- [x] Ensure transition between day and night lighting.

## Additional Information
No additional information.
