### ISSUE TITLE
Implement Drone Controls

### ISSUE THREAD

**Issue by TobiasGoetz** [DHBW-FN/tim21-computer-graphics#27]
# User Story
**As a** front-end developer,
**I want** to implement controls for the drone's movement,
**So that** users can navigate the drone around the Eiffel Tower.

## Acceptance Criteria
- [x] Drone movement controls are functional.
- [x] Users can effectively control the drone's movement.

## Tasks
- [x] Add event listeners for drone controls.
- [x] Map controls to corresponding drone actions.

## Additional Information
No additional information.
