### ISSUE TITLE
Implement Animations

### ISSUE THREAD

**Issue by TobiasGoetz** [DHBW-FN/tim21-computer-graphics#29]
# User Story
**As a** front-end developer,
**I want** to implement additional animations
**So that** users have more moving things to looks at.

## Acceptance Criteria
- [x] Additional animations are rendered
- [x] The animations are visible and loop well
- [x] At least 1 car (prefferrably more)
- [x] Optional A plane
- [x] Birds
- [x] Optional Water

## Tasks
- [x] Find/Create Models
- [x] Animate models in Three.JS
- [x] Make the animations loop/restart

## Additional Information
No additional information.
