### ISSUE TITLE
Project Setup

### ISSUE THREAD

**Issue by TobiasGoetz** [DHBW-FN/tim21-computer-graphics#3]
# Epic
Setting up the project and defining initial design choices.

## Acceptance criteria

- [x] GitHub repository created with initial commit.
- [x] Project structure and file organization defined.
- [x] Development tools (Blender, Three.js, etc.) chosen and configured.
- [x] Reference materials for the Eiffel Tower model gathered.
