### ISSUE TITLE
Fine-tune

### ISSUE THREAD

**Issue by TobiasGoetz** [DHBW-FN/tim21-computer-graphics#30]
# User Story
**As a** front-end developer,
**I want** to fine-tune the user interface for optimal user experience,
**So that** users can navigate and interact with the scene seamlessly.

## Acceptance Criteria
- [x] Users can easily access and utilize controls.
- [x] Street lamps have lights attached

## Tasks
- [x] Review and adjust layout for improved aesthetics.
- [x] Test UI elements for responsiveness and ease of use.
- [x] Add lights(e.g. directional or point) to street lamps

## Additional Information
The most important streetLamps `[5, 6, 7, 8, 14, 15, 19, 20, 21, 22, 23, 24, 25]`

### Abandoned features
- Loading screen
- sun off center for nicer looking shadows
