### ISSUE TITLE
Create Presentation Materials

### ISSUE THREAD

**Issue by TobiasGoetz** [DHBW-FN/tim21-computer-graphics#33]
# User Story
**As a** team member,
**I want** to create presentation materials (slides) covering project overview, design choices, and demo,
**So that** we can effectively communicate our project to the audience.

## Acceptance Criteria
- [x] Presentation slides are created covering project overview and design choices.
- [x] Demo of the project is included in the presentation.

## Tasks
- [x] Develop slides for project overview.
- [x] Explain design choices and implementation details.
- [x] Include a demo of the project in the presentation.

## Additional Information
No additional information.
