### ISSUE TITLE
Gather Reference Materials

### ISSUE THREAD

**Issue by TobiasGoetz** [DHBW-FN/tim21-computer-graphics#35]
# User Story
**As a** designer,
**I want** to research and gather reference materials for the Eiffel Tower model,
**So that** we can create an accurate and detailed 3D model.

## Acceptance Criteria
- [x] Reference images, blueprints, and other materials related to the Eiffel Tower are collected and organized.

## Tasks
- [x] Research and collect reference images of the Eiffel Tower.
- [x] Gather any available blueprints or diagrams for accuracy.

### General
![Layout](https://github.com/DHBW-FN/tim21-computer-graphics/assets/26843910/c85f7694-f36a-4df7-99b0-024b53c988c8)

#### Eiffel tower
[free-la-tour-eiffel.zip](https://github.com/DHBW-FN/tim21-computer-graphics/files/13125409/free-la-tour-eiffel.zip)

### Materials
[materials.zip](https://github.com/DHBW-FN/tim21-computer-graphics/files/13125421/materials.zip)
