### ISSUE TITLE
Add skybox to scene

### ISSUE THREAD

**Issue by philippkuest** [DHBW-FN/tim21-computer-graphics#47]
# User Story
**As a** front-end developer,
**I want** to have a sky,
**So that** users can see the sky.

## Acceptance Criteria
- [x] skybox created
- [x] images downloaded and added to scene

## Tasks
- [x] Find and download skybox image
- [x] implement skybox in three js

## Additional information
[Skybox tool](https://tools.wwwtyro.net/space-3d/index.html#animationSpeed=0&fov=150&nebulae=false&pointStars=true&resolution=1024&seed=289347&stars=true&sun=false)
