### ISSUE TITLE
ModelLoader dynamic position and rotation

### ISSUE THREAD

**Issue by TobiasGoetz** [DHBW-FN/tim21-computer-graphics#50]
# User Story
**As a** developer,
**I want** to be able to pass position and rotation to the ModelLoader,
**So that** I can easily load models at specific positions.

## Acceptance Criteria
- [x] ModelLoader is able to load a model at a specific location
- [x] ModelLoader is able to load a model with a specific rotation
- [x] ModelLoader still creates collision objects

## Tasks
- [x] Change modelloader to accept location x/y/z and set the loaded models position to this
- [x] Change modelloader to accept rotation x/y/z and set the loaded models rotation to this

### New mode JSON schema
- Here you can see 3 different instances of loading the same model.
- All values of an instance are optional and if not provided it just uses coordinates/rotation from the gltf/glb file
- `collidable` defaults to `true` if not supplied
- as you can see even an empty instance creates an object, this is used e.g. for the base world

```json
{
  "base": {
    "path": "assets/models/world/World.gltf",
    "instances": [
      {
        "position": { "x": 0, "y": 0, "z": 0 },
        "rotation": { "x": 0, "y": 0, "z": 0 },
        "scale": { "x": 1, "y": 1, "z": 1 },
        "collidable": true,
        "castShadow": true,
        "receiveShadow": true,
      },
      {
        "position": { "x": 1, "y": 2, "z": -1 },
        "rotation": { "x": 0, "y": 1, "z": 0 },
        "scale": { "x": 0.5, "y": 0.5, "z": 0.5 },
        "collidable": false
      },
      {}
    ]
  }
}
```
