### ISSUE TITLE
Camera and Drone Functionality

### ISSUE THREAD

**Issue by TobiasGoetz** [DHBW-FN/tim21-computer-graphics#6]
# Epic
Implementing camera and drone control features.

## Acceptance criteria

- [x] Drone movement controls integrated.
- [x] Drone camera enables 360-degree viewing of the Eiffel Tower.
- [x] Secondary stationary camera for overview shots.
- [x] Collision detection of drone
