### ISSUE TITLE
Lighting and Day-Night Cycle

### ISSUE THREAD

**Issue by TobiasGoetz** [DHBW-FN/tim21-computer-graphics#7]
# Epic
Adding lighting effects and simulating day-night transitions.

## Acceptance criteria

- [x] Daylight simulated with a sunlight source.
- [x] Night lighting implemented with a spotlight.
- [x] Seamless transition between day and night.
