### ISSUE TITLE
Interactivity and Fine-tuning

### ISSUE THREAD

**Issue by TobiasGoetz** [DHBW-FN/tim21-computer-graphics#9]
# Epic
Implementing additional interactions and fine-tuning user experience.

## Acceptance criteria

- [x] Additional interactions like object picking and zooming.
- [x] User interface fine-tuned for optimal experience.
- [x] Application tested for performance and stability.
